export const mockStakingPools = [
  // Real pools from screenshot
  {
    id: '1',
    name: 'CETUS-SUI',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 5640000,
    baseApy: 125,
    apy: 157,
    avgApy30d: 125,
  },
  {
    id: '2',
    name: 'USDC-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 1500000,
    baseApy: 222,
    apy: 254,
    avgApy30d: 222,
  },
  {
    id: '3',
    name: 'CETUS',
    projectName: 'NAVI Lending',
    projectIcon: '/images/projects/navi.png',
    tvl: 1020000,
    baseApy: 0.41,
    apy: 0.41,
    avgApy30d: 0.41,
  },
  {
    id: '4',
    name: 'NAVI-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 230992,
    baseApy: 41.13,
    apy: 41.13,
    avgApy30d: 41.13,
  },
  {
    id: '5',
    name: 'CETUS-TURBOS',
    projectName: 'Turbos',
    projectIcon: '/images/projects/turbos.png',
    tvl: 125856,
    baseApy: 69.65,
    apy: 69.65,
    avgApy30d: 69.65,
  },
  // Additional mock pools to test scrolling
  {
    id: '6',
    name: 'PYTH-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 124737,
    baseApy: 40.90,
    apy: 88.20,
    avgApy30d: 40.90,
  },
  {
    id: '7',
    name: 'CETUS',
    projectName: 'Scallop Lend',
    projectIcon: '/images/projects/scallop.png',
    tvl: 115983,
    baseApy: 0.58,
    apy: 0.58,
    avgApy30d: 0.58,
  },
  {
    id: '8',
    name: 'JWLCETUS-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 82810,
    baseApy: 0.54,
    apy: 5.72,
    avgApy30d: 0.54,
  },
  {
    id: '9',
    name: 'YOT-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 32702,
    baseApy: 1.17,
    apy: 1.17,
    avgApy30d: 1.17,
  },
  {
    id: '10',
    name: 'SUIA-CETUS',
    projectName: 'Cetus AMM',
    projectIcon: '/images/projects/cetus.png',
    tvl: 32010,
    baseApy: 13.01,
    apy: 13.01,
    avgApy30d: 13.01,
  },
];
