import React from 'react';
import { FileText } from 'lucide-react';

interface TokenSummaryProps {
  data: {
    summary: string;
    agent: string;
    score: number;
  };
}

export const TokenSummary: React.FC<TokenSummaryProps> = ({ data }) => {
  return (
    <div className="bg-gray-900 rounded-lg p-6 h-full">
      <div className="flex items-center gap-2 mb-4">
        <FileText className="text-purple-500" size={20} />
        <h3 className="text-lg font-medium">Token Summary</h3>
      </div>
      
      <div className="bg-gray-800 p-4 rounded-lg h-[calc(100%-4rem)]">
        <div className="flex justify-between items-start mb-4">
          <div className="text-sm text-gray-400">Generated by {data.agent}</div>
          <div className="bg-purple-500/20 text-purple-400 px-2 py-1 rounded text-sm">
            Score: {data.score}
          </div>
        </div>
        
        <div className="prose prose-invert prose-sm max-w-none">
          <p>{data.summary}</p>
        </div>
      </div>
    </div>
  );
};
